services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: proyecto-final:latest
    ports:
      - "7070:7070"
    env_file:
      - .env
    environment:
      PORT: ${PORT:-7070}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

